apiVersion: v1
kind: Pod
metadata:
  name: gateway
  namespace: dev
  labels:
    component: gateway
spec:
   #nodeSelector: # 使用节点选择器将Pod调度到指定label的节点
   #    component: demo
  containers:
    - name: gateway 
      image: 47.104.2.213:5000/gateway:1.0
      ports:
        - containerPort: 8088
