apiVersion: v1
kind: Pod
metadata:
  name: springcloud
  namespace: dev
  labels:
    component: order
spec:
  #nodeSelector: # 使用节点选择器将Pod调度到指定label的节点
  #   component: demo
  containers:
    - name: order
      image: 47.104.2.213:5000/order:1.0
      ports:
        - containerPort: 8010
