FROM openjdk:8u312-jdk-oraclelinux7
ADD order-0.0.1-SNAPSHOT.jar /home/springboot/order/order-0.0.1-SNAPSHOT.jar
EXPOSE 8010
ENTRYPOINT ["java","-jar","/home/springboot/order/order-0.0.1-SNAPSHOT.jar"]