server:
  port: 8010
spring:
  application:
    name: order-service
  profiles:
    active: dev
  cloud:
#    nacos:
#      discovery:
#        server-addr: 120.79.2.76:8847
#        username: nacos
#        password: nacos
    stream:
      default-binder: rabbit
      rabbit:
        bindings:
          ORDER_SETTLE_TO_STOCK_OUTPUT:
            producer:
              confirmAckChannel: streamAckCallBack
              autoBindDlq: true
              deadLetterExchange: WAITING_EXCHANGE
              deadLetterQueueName: OCMS_WAITING_QUEUE
              dlqTtl: 5000
              dlqDeadLetterExchange:
      bindings:
        ORDER_SETTLE_TO_STOCK_OUTPUT:
          destination: ORDER_SETTLE_TO_STOCK
          producer:
            partitionKeyExpression: headers['partitionKey']
            partitionCount: 1
            requiredGroups: group
            errorChannelEnabled: true
  redis:
    host: 120.79.2.76
    #MTIzNDU2
    password: 123456
    port: 6379
  #namespace: dev #大方向设置开发 测试 和 生产环境
        #group: ocms  #可以设置不同得项目组
        #ephemeral: false #永久示例，即使服务宕机了 也不会经过30秒从服务列表中删除,管理界面有保护阈值得设置，为了防止服务雪崩，一般不用
#    jedis:
#      pool:
#        max-active: 1
#        max-idle: 1
#        max-wait: -1
#        min-idle: 1
#基于配置nacosrule 随机+权重
#stock-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule

#启动得时候就会去加载，并不是第一次去调用去加载
#ribbon:
#  eager-load:
#    #开启饥饿加载
#    enabled: true
#    clients: stock-service
#springboot 默认info ，feign得日志级别是debug
#logging:
#  level:
#    com.demo.service.StockFeignService: debug
  rabbitmq:
    host: 120.79.2.76
    port: 5672
    username: zsr
    password: 123456
    publisher-returns: false
    publisher-confirm-type: correlated
  datasource:
    druid:
      url: jdbc:mysql://120.79.2.76:3306/order?autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf-8&useSSL=false&useOldAliasMetadataBehavior=true&serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL&netTimeoutForStreamingResults=0&connectTimeout=2000
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource


