server:
  port: 8011
spring:
  application:
    name: stock-service
  redis:
    host: 120.79.2.76
    #MTIzNDU2
    password: 123456
    port: 6379
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 120.79.2.76:8847
#        username: nacos
#        password: nacos
        #namespace: public #大方向设置开发 测试 和 生产环境
        #group: ocms  #可以设置不同得项目组
        #ephemeral: false #永久示例，即使服务宕机了 也不会经过30秒从服务列表中删除,管理界面有保护阈值得设置，为了防止服务雪崩，一般不用